---
- hosts: localhost
  connection: local
  tasks:
  - name: Create a resource group
    azure_rm_resourcegroup:
      name: bot-group-01
      location: southuk
      tags:
         testing: testing
          delete: never
