---
- hosts: localhost
  connection: local
  tasks:

  - name: Create a resource group
    azure_rm_resourcegroup:
      name: bot-group-01
      location: southuk
      tags:
         testing: testing
          delete: never

  - name: Get facts for all resource groups
    azure_rm_resourcegroup_info:

  - name: create bot 
    shell: |
      az bot prepare-deploy --lang Javascript --code-dir "MyBotCode"
